### ISSUE TITLE
Basic Auth fails if password contains ":"

### ISSUE THREAD

**Issue by warren-oneill** [plotly/dash-auth#104]
I get the following error in `dash_auth/basic_auth.py` if I use a password that contains a colon:
`
line 19, in is_authorized
username, password = username_password_utf8.split(':')
ValueError: too many values to unpack (expected 2)`

A solution could be to keep the user/pass pair as a dictionary or convert to a dictionary and covert back.

**Comment by kevbroch** [comment]
Should be fixed in #83 

I just tested it worked by changing [example code](https://github.com/plotly/dash-auth/blob/master/usage_basic_auth.py) to:

```python
VALID_USERNAME_PASSWORD_PAIRS = {
    'hello': 'wor:ld'
}
```

**Comment by warren-oneill** [comment]
Thanks @kevbroch! Worked when I upgraded to version 1.4.1.
