### ISSUE TITLE
Basic auth prompt does not appear on sub pages, only on main page, browser displays blank page

### ISSUE THREAD

**Issue by jamaa** [plotly/dash-auth#139]
I have a multi-page dash app using [Dash Pages](https://dash.plotly.com/urls#dash-pages) that I have added basic authentication to as described [here](https://dash.plotly.com/authentication#basic-auth). 

The issue I have is that the prompt for authentication only appears when I visit the main/home page. If I am not already logged in and visit one of the sub pages by entering its URL directly, no authentication prompt appears and the browser just displays a blank page.

I would expect the authentication prompt to also appear when visiting one of the sub pages directly.

**Comment by alexcjohnson** [comment]
v2.1.0 fixed this issue, and v2.2.0 brings the ability to whitelist certain routes that should bypass auth. Thanks @RenaudLN for both contributions!
