### ISSUE TITLE
Plotly POST operations turn to 403 after a minute with auth activated

### ISSUE THREAD

**Issue by xapple** [plotly/dash-auth#50]
When using the basic HTTP Auth with following code:

    VALID_USERNAME_PASSWORD_PAIRS = [('example', 'hunter2')]
    auth = dash_auth.BasicAuth(app, VALID_USERNAME_PASSWORD_PAIRS)

I get 403 responses when clicking on the application's elements that have callbacks attached, after a while. The problem disappears completely if I comment-out the above lines of code.

What is strange is that the problem manifests itself only after clicking a certain number of times on elements in the dash app that have callbacks, such that the server stdout looks like this:

    127.0.0.1 - - [31/Jul/2018 21:52:10] "POST /_dash-update-component HTTP/1.1" 200 -
    127.0.0.1 - - [31/Jul/2018 21:52:10] "POST /_dash-update-component HTTP/1.1" 200 -
    127.0.0.1 - - [31/Jul/2018 21:52:13] "POST /_dash-update-component HTTP/1.1" 200 -
    127.0.0.1 - - [31/Jul/2018 21:52:19] "POST /_dash-update-component HTTP/1.1" 200 -
    127.0.0.1 - - [31/Jul/2018 21:52:22] "POST /_dash-update-component HTTP/1.1" 403 -
    127.0.0.1 - - [31/Jul/2018 21:52:25] "POST /_dash-update-component HTTP/1.1" 403 -

The above log is produced by repeatedly clicking on the same element.

Once a call to `/_dash-update-component` turns to 403 it remains like that forever, until the user reloads the whole web page.

**Comment by olivier-lacroix** [comment]
This has likely been fixed by release 2.1 @alexcjohnson
