### ISSUE TITLE
AWS deployment -  Login username/password details not accepted

### ISSUE THREAD

**Issue by natisangarita** [plotly/dash-auth#58]
Hi . I have been trying to deploy the dash basic login.

Whilst it works fine locally, once deployed to AWS ( using Beanstalk), the login window keep appearing  after entering the right login details.
The login details are never validated. 

I have successfully deployed the same app without the loging part.
I also tried to deploy the dash_login example with no luck ( again it runs fine locally, and the same problem occurs).

The logs  are below. Any help much appreciated. 
I have managed to deploy a basic Flask login module but I have yet to learn how to mask urls, etc.
I would rather use the dash_auth module if possible. 

Thanks
PD: After reading in the community forum I found that the problem  was also reported when deploying in  digital ocean 

-------------------------------------
/var/log/httpd/error_log
-------------------------------------
[Sun Sep 02 01:53:54.118596 2018] [suexec:notice] [pid 3088] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sun Sep 02 01:53:54.133927 2018] [http2:warn] [pid 3088] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Sep 02 01:53:54.133937 2018] [http2:warn] [pid 3088] AH02951: mod_ssl does not seem to be enabled
[Sun Sep 02 01:53:54.134327 2018] [lbmethod_heartbeat:notice] [pid 3088] AH02282: No slotmem from mod_heartmonitor
[Sun Sep 02 01:53:54.134369 2018] [:warn] [pid 3088] mod_wsgi: Compiled for Python/3.6.2.
[Sun Sep 02 01:53:54.134372 2018] [:warn] [pid 3088] mod_wsgi: Runtime using Python/3.6.5.
[Sun Sep 02 01:53:54.136211 2018] [mpm_prefork:notice] [pid 3088] AH00163: Apache/2.4.33 (Amazon) mod_wsgi/3.5 Python/3.6.5 configured -- resuming normal operations
[Sun Sep 02 01:53:54.136226 2018] [core:notice] [pid 3088] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sun Sep 02 01:55:22.308807 2018] [mpm_prefork:notice] [pid 3088] AH00169: caught SIGTERM, shutting down
[Sun Sep 02 01:55:23.394411 2018] [suexec:notice] [pid 3534] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sun Sep 02 01:55:23.409282 2018] [so:warn] [pid 3534] AH01574: module wsgi_module is already loaded, skipping
[Sun Sep 02 01:55:23.411264 2018] [http2:warn] [pid 3534] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Sep 02 01:55:23.411274 2018] [http2:warn] [pid 3534] AH02951: mod_ssl does not seem to be enabled
[Sun Sep 02 01:55:23.411814 2018] [lbmethod_heartbeat:notice] [pid 3534] AH02282: No slotmem from mod_heartmonitor
[Sun Sep 02 01:55:23.411875 2018] [:warn] [pid 3534] mod_wsgi: Compiled for Python/3.6.2.
[Sun Sep 02 01:55:23.411879 2018] [:warn] [pid 3534] mod_wsgi: Runtime using Python/3.6.5.
[Sun Sep 02 01:55:23.414057 2018] [mpm_prefork:notice] [pid 3534] AH00163: Apache/2.4.33 (Amazon) mod_wsgi/3.5 Python/3.6.5 configured -- resuming normal operations
[Sun Sep 02 01:55:23.414071 2018] [core:notice] [pid 3534] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sun Sep 02 01:55:27.036415 2018] [:error] [pid 3539] /opt/python/run/venv/local/lib/python3.6/site-packages/plotly/tools.py:102: UserWarning:
[Sun Sep 02 01:55:27.036444 2018] [:error] [pid 3539] 
[Sun Sep 02 01:55:27.036448 2018] [:error] [pid 3539] Looks like you don't have 'read-write' permission to your 'home' ('~') directory or to our '~/.plotly' directory. That means plotly's python api can't setup local configuration files. No problem though! You'll just have to sign-in using 'plotly.plotly.sign_in()'. For help with that: 'help(plotly.plotly.sign_in)'.
[Sun Sep 02 01:55:27.036451 2018] [:error] [pid 3539] Questions? Visit https://support.plot.ly
[Sun Sep 02 01:55:27.036454 2018] [:error] [pid 3539] 

-------------------------------------
/opt/python/log/supervisord.log
-------------------------------------
2018-09-02 01:53:52,915 CRIT Supervisor running as root (no user in config file)
2018-09-02 01:53:52,957 INFO RPC interface 'supervisor' initialized
2018-09-02 01:53:52,957 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-09-02 01:53:52,957 INFO supervisord started with pid 3002
2018-09-02 01:53:53,963 INFO spawned: 'httpd' with pid 3088
2018-09-02 01:53:55,118 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-02 01:55:22,321 INFO stopped: httpd (exit status 0)
2018-09-02 01:55:23,326 INFO spawned: 'httpd' with pid 3534
2018-09-02 01:55:24,393 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by T4rk1n** [comment]
You need the Plotly credentials for `PlotlyOauth`. You can set the following environ vars in your Elastic Beanstalk settings.

- `PLOTLY_USERNAME` your https://plot.ly username.
- `PLOTLY_API_KEY` The api key you find in the settings, you may need to reset it to view.

You also need a subscription.

**Comment by glennlawyer** [comment]
@natisangarita 
I'm not sure @T4rk1n's answer is the only way, or even fully correct.

The problem may be caused by how AWS handles passing the HTTP authorisation headers through to a WSGI application. You need to configure your AWS environment such that the config variable `WSGIPassAuthorization` is set to `On`.

One way to do this is to create (in the top folder of your Dash project) a folder called `.ebextensions` with the file `wsgi_custom.config`. The name matters, because AWS looks for this specific file. 

The file should contain a YAML script creating a config file which sets the variable. So:

Create the file
```
.ebextensions/wsgi_custom.config
```
with the following content
```
files:
     "/etc/httpd/conf.d/wsgi_custom.conf":
          mode: "000644"
          owner: root
          group: root
          content: |
              WSGIPassAuthorization On
````

See discussion here
`https://community.plot.ly/t/how-do-i-deploy-dash-to-elastic-beanstalk-with-basic-authentication/11676/5`
and here
`https://stackoverflow.com/questions/22279301/authorization-credentials-stripped-django-elastic-beanstalk-oauth`
