### ISSUE TITLE
Support for additional OAuth providers

### ISSUE THREAD

**Issue by brylie** [plotly/dash-auth#66]
Please allow support for, or document how to add, [third-party OAuth providers](https://en.wikipedia.org/wiki/List_of_OAuth_providers). E.g. logging in with:

- GitHub
- Google

While it is understandable that Plot.ly needs to build a business model around Dash, it would be appreciated that it not preclude federated authentication for Dash apps.

**Comment by olivier-lacroix** [comment]
Will be closed by https://github.com/plotly/dash-auth/pull/145
