### ISSUE TITLE
Change passwords

### ISSUE THREAD

**Issue by wwerst** [plotly/dash-auth#84]
Test user passwords weren't rolled for dash-test-viewer (and maybe others??) after #80 which removed them from being hardcoded. Guessing Plotly team would be interested in this. I think you should roll this test user password.

**Comment by wwerst** [comment]
@scjody @T4rk1n Can you take a look at this?

**Comment by scjody** [comment]
@wwerst Thanks for pointing this out!

@alexcjohnson Can you please find someone on your team who can do this?

**Comment by alexcjohnson** [comment]
Thanks @wwerst - yes @scjody we will take care of it.

**Comment by banyous** [comment]
Hi, any updates on this issue?

**Comment by alexcjohnson** [comment]
Now you can authenticate with a function instead of a static map, and this function can refresh either every time or periodically, as desired.
