### ISSUE TITLE
unable to authenticate with user and password from tutorial

### ISSUE THREAD

**Issue by Laneville** [plotly/dash-auth#85]
I set up my dash-auth exactly how the sample code shows in the [dash.plot.ly](https://dash.plot.ly/authentication) authentication page. However, when entering in the 'hello' and 'world' username and password, it simply won't log in to the demo graph page. Any ideas?

My dash versions are exactly as shown in the tutorial:
dash - 1.0.2
dash-auth = 1.2.0

This is the code from the tutorial and I am running python index.py

`import dash
import dash_auth
import dash_core_components as dcc
import dash_html_components as html
import plotly

# Keep this out of source code repository - save in a file or a database
VALID_USERNAME_PASSWORD_PAIRS = {
    'hello': 'world'
}

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
auth = dash_auth.BasicAuth(
    app,
    VALID_USERNAME_PASSWORD_PAIRS
)

app.layout = html.Div([
    html.H1('Welcome to the app'),
    html.H3('You are successfully authorized'),
    dcc.Dropdown(
        id='dropdown',
        options=[{'label': i, 'value': i} for i in ['A', 'B']],
        value='A'
    ),
    dcc.Graph(id='graph')
], className='container')

@app.callback(
    dash.dependencies.Output('graph', 'figure'),
    [dash.dependencies.Input('dropdown', 'value')])
def update_graph(dropdown_value):
    return {
        'layout': {
            'title': 'Graph of {}'.format(dropdown_value),
            'margin': {
                'l': 20,
                'b': 20,
                'r': 10,
                't': 60
            }
        },
        'data': [{'x': [1, 2, 3], 'y': [4, 1, 2]}]
    }

if __name__ == '__main__':
    app.run_server(debug=True)`

**Comment by Laneville** [comment]
This is the code from the tutorial and I am running python index.py

`import dash
import dash_auth
import dash_core_components as dcc
import dash_html_components as html
import plotly

# Keep this out of source code repository - save in a file or a database
VALID_USERNAME_PASSWORD_PAIRS = {
    'hello': 'world'
}

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
auth = dash_auth.BasicAuth(
    app,
    VALID_USERNAME_PASSWORD_PAIRS
)

app.layout = html.Div([
    html.H1('Welcome to the app'),
    html.H3('You are successfully authorized'),
    dcc.Dropdown(
        id='dropdown',
        options=[{'label': i, 'value': i} for i in ['A', 'B']],
        value='A'
    ),
    dcc.Graph(id='graph')
], className='container')

@app.callback(
    dash.dependencies.Output('graph', 'figure'),
    [dash.dependencies.Input('dropdown', 'value')])
def update_graph(dropdown_value):
    return {
        'layout': {
            'title': 'Graph of {}'.format(dropdown_value),
            'margin': {
                'l': 20,
                'b': 20,
                'r': 10,
                't': 60
            }
        },
        'data': [{'x': [1, 2, 3], 'y': [4, 1, 2]}]
    }

if __name__ == '__main__':
    app.run_server(debug=True)`

**Comment by Rockraider** [comment]
Got the same problem, changing the valid user/pass pairs to a list of tuple worked for me:
`VALID_USERNAME_PASSWORD_PAIRS = [('hello', 'world')]`
or for multiple credentials:
`VALID_USERNAME_PASSWORD_PAIRS = [('hello', 'world'), ('foo', 'bar')]`

**Comment by benjamincerigo** [comment]
I also had a similar problem with this tutorial: https://dash.plot.ly/authentication. The version of dash-auth that works with a dictionary instead of an array of tuples is 1.3.2. Thus the version of dash-auth for that tutorial should be > 1.3.2.

The tutorial states that dash-auth==1.2.0 should be installed however this does not work with the code that is given. Would be awesome if the tutorial could be updated!

Maybe the version change should have been major (2.0.0)? See https://semver.org/.

**Comment by wobo-bhavin** [comment]
Thanks @benjamincerigo , upgrading to 1.3.2 resolved it for me. A simple edit in the documentation will allow this to be closed.
