### ISSUE TITLE
customize BasicAuth css

### ISSUE THREAD

**Issue by romainmartinez** [plotly/dash-auth#86]
Hi and thanks for the dash framework.

I use `BasicAuth` and I'd like it to look like [this bootstrap example](https://getbootstrap.com/docs/4.3/examples/sign-in/).
Is it possible to customize the `BasicAuth` css?

**Comment by alexcjohnson** [comment]
AFAICT this is not possible - the basic auth dialog does not seem to be HTML/CSS, rather it's a built-in browser feature.
