### ISSUE TITLE
No module named 'plotly_auth'

### ISSUE THREAD

**Issue by Tatooin3** [plotly/dash-auth#9]
I am using Anaconda with a python 3.4 virtual environment.
When I try to import the module **dash_auth**, I get the following error:

```
Traceback (most recent call last):
  File "inputs.py", line 6, in <module>
    import dash_auth as dauth
  File "C:\Users\pierre\AppData\Local\Continuum\Anaconda2\envs\py34env\lib\site
-packages\dash_auth\__init__.py", line 1, in <module>
    from plotly_auth import PlotlyAuth
ImportError: No module named 'plotly_auth'
```
Although Python tells me that there no module named _'plotly_auth'_, when I look in the **dash_auth** folder I can see the plotly_auth file.
I don't have this issue when I import **dash_auth** in a Python 2.7 environment.

**Comment by chriddyp** [comment]
Thanks for reporting @Tatooin3 ! This is pretty odd: we're testing python36 in the integration tests so I'm surprised that py34 would behave differently.

I'll start by attempting to reproduce the issue by adding python34 to our integration tests: https://github.com/plotly/dash-auth/pull/11

**Comment by chriddyp** [comment]
It doesn't look like the python3.4 tests are having any issues with the package. I wonder if this has to do with the package distribution itself, like the `.pyc` files, as I create the `sdist` with python2. I haven't seen this issue in any other packages though...

**Comment by chriddyp** [comment]
From https://stackoverflow.com/questions/2263356/are-python-2-5-pyc-files-compatible-with-python-2-6-pyc-files

> In general, .pyc files are specific to one Python version (although portable across different machine architectures, as long as they're running the same version); the files carry the information about the relevant Python version in their headers -- so, if you leave the corresponding .py files next to the .pyc ones, the .pyc will be rebuilt every time a different Python version is used to import those modules.

OK, so my distribution shouldn't be the problem here. 

> This can be a real problem if you ever find yourself continuously trying to run a single set of .py files from two or more different versions of Python (even on the same server, without the added complications of network drives). The "proper" solution would be something like virtualenv.

Does this apply to your situation @Tatooin3 ?

Finally, does installing the package manually work for you?
```
git clone https://github.com/plotly/dash-auth
cd dash-auth
python setup.py install
```

**Comment by Tatooin3** [comment]
Sorry for delay and thank you for your response @chriddyp . 
Yes it is indeed my case. I have Python 2.7 and 3.4 installed on my computer. Nevertheless, I use anaconda with 2 different virtualenvs. I have checked and the library that gets imported is the right one in both cases.
I will try to install the package manually and will let you know.
