### ISSUE TITLE
Specify hashing to use encrypted database

### ISSUE THREAD

**Issue by Zylatis** [plotly/dash-auth#95]
My understanding is that the current implementation reads in login/pw pairs where it will do a direct comparison of the pw in plain text with whatever is entered. However, I would like to connect to a db which stored hashed passwords and then hash the user input and compare.

How hard would it be to implement functionality to also define an arbitrary python function which the user can define which will be used for this hashing and comparison?

**Comment by hoadcoder** [comment]
Hey, did you get any solution for this? I've run into the same sisue right now.

**Comment by michaels0m** [comment]
This should now be possible with the latest release v2.1.0

**Comment by alexcjohnson** [comment]
Yep, the ability to pass a function instead of a static map for to test against allows you to store passwords hashed. Thanks @michaels0m for the contribution!
